---
deployment:
  tasks:
    - export DEPLOYPATH=/home/betkvqwf/public_html/
    - /bin/cp /home/betkvqwf/git/The-Lukesters-Portfolio/PortfolioSite/index.html $DEPLOYPATH
    - /bin/cp /home/betkvqwf/git/portfolio/stash/error-page.html $DEPLOYPATH
    - /bin/cp /home/betkvqwf/git/portfolio/stash/parallax.html $DEPLOYPATH
    - /bin/cp /home/betkvqwf/git/portfolio/stash/robots.txt $DEPLOYPATH
    - /bin/cp /home/betkvqwf/git/portfolio/stash/send-mail.php $DEPLOYPATH
    - /bin/cp /home/betkvqwf/git/portfolio/stash/sitemap.xml $DEPLOYPATH
    - /bin/cp /home/betkvqwf/git/portfolio/stash/thank-you.html $DEPLOYPATH
    - /bin/cp /home/betkvqwf/git/portfolio/stash/css/main.css $DEPLOYPATH
    - /bin/cp /home/betkvqwf/git/portfolio/stash/css/main.min.css $DEPLOYPATH